FROM python:3

WORKDIR /usr/src/app

RUN apt update
RUN apt install vim -y

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY ./decrypt.py functs.py ./

# CMD [ "./decrypt.py", "myjson.xml" ]
CMD bash
